name: edgecube_app
description: Minecraft Server Manager
homepage: https://edgecubemc.com
repository: https://github.com/venti1112/EdgeCube
issue_tracker: https://github.com/venti1112/EdgeCube/issues
documentation: https://edgecubemc.com/#docs
publish_to: 'none'
platforms:
  android:
  windows:
  linux:
  web:

version: 2.0.0+200

environment:
  sdk: ">=3.12.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.9
  flutter_riverpod: ^3.4.3
  go_router: ^18.0.1
  material_ui: ^1.2.0
  shared_preferences: ^2.5.5
  dynamic_color: ^2.1.0
  file_picker: ^13.1.0
  path_provider: ^2.1.6
  flex_color_picker: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
