name: edgecube
description: Minecraft Server Tool
homepage: https://edgecubemc.com
repository: https://github.com/venti1112/EdgeCube
issue_tracker: https://github.com/venti1112/EdgeCube/issues
documentation: https://edgecubemc.com/#docs
publish_to: 'none'
platforms:
  android:
  windows:
  linux:
  web:

version: 2.0.0+200

environment:
  sdk: ">=3.12.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
